####################################
# The following are general settings
####################################

# Experiment name, more details in Section 'Experiment Name Explanation'
NAME: vae_session_1
# Debug mode. Set to True will enter the debug mode, then the program will
# 1. use a tiny dataset for trianing and evaluation
# 2. validate more intensively
# 3. will not use `wandb logger`
DEBUG: False
# Devices. Optional: “cpu”, “gpu”
ACCELERATOR: 'gpu'
# Index of GPUs eg. [0] or [0,1,2,3]
DEVICE: [0,1]

#####################################
# The following are training settings
#####################################
TRAIN:
  # Model stage. Optional: "vae", "diffusion"
  STAGE: vae
  # Training dataset name
  DATASETS: ['ubnormal']
  # Number of dataloader workers
  NUM_WORKERS: 4
  # Size of batches
  BATCH_SIZE: 512
  # Total epochs for training
  END_EPOCH: 20

  RESUME: '' # Resume training from this path
  PRETRAINED_VAE: '' # vae model path
  OPTIM:
    TYPE: AdamW # Optimizer type
    LR: 1e-4 # Learning rate
  # Ablation study configurations.
  ABLATION:
    SKIP_CONNECT: True
    PE_TYPE: mld
    DIFF_PE_TYPE: mld
    BATCH_FIRST: False # batch is the first dimension

#####################################
# The following are validation settings
#####################################
EVAL:
  DATASETS: ['ubnormal'] # Evaluating datasets
  BATCH_SIZE: 32 # Evaluating Batch size
  SPLIT: test

#####################################
# The following are testing settings
#####################################
TEST:
  CHECKPOINTS: ./models/mld_ubnormal_checkpoint/1222_mld_ubnormal_FID041.ckpt # Pretrained model path
  DATASETS: ['ubnormal'] # training datasets
  SPLIT: test
  BATCH_SIZE: 1 # training Batch size
  MEAN: False
  NUM_SAMPLES: 1
  FACT: 1

#####################################
# The following are basic datasets settings
#####################################
DATASET:
  JOINT_TYPE: 'mmm' # join type

#####################################
# The following are metric settings
#####################################
METRIC:
  TYPE: []

#####################################
# The following are training losses settings
#####################################
LOSS:
  TYPE: mld # Losses type
  LAMBDA_LATENT: 1.0e-5 # Lambda for latent Losses
  LAMBDA_KL: 1.0e-4 # Lambda for kl Losses
  LAMBDA_REC: 0.0 # Lambda for reconstruction Losses
  LAMBDA_JOINT: 1.0 # Lambda for joint losses
  LAMBDA_GEN: 0.0 # Lambda for text-motion generation losses
  LAMBDA_CROSS: 0.0 # Lambda for reconstruction Losses
  LAMBDA_CYCLE: 0.0 # Lambda for cycle Losses
  LAMBDA_PRIOR: 0.0
  DIST_SYNC_ON_STEP: False # Sync Losses on step when distributed trained

#####################################
# The following are basic model settings
#####################################
model:
  vae: true # whether vae model
  model_type: mld # model type
  condition: null
  latent_dim: [1, 16] # latent dimension
  ff_size: 256 # understand what's this
  num_layers: 4 # number of layers
  num_head: 3 # number of head layers
  droupout: 0.1 # dropout rate
  activation: gelu # activation type
  guidance_scale: 7.5 #
  guidance_uncondp: 0.1 # 0.1 0.25

#####################################
# The following are loggers settings
#####################################
LOGGER:
  SACE_CHECKPOINT_EPOCH: 200
  LOG_EVERY_STEPS: 1
  VAL_EVERY_STEPS: 200
  TENSORBOARD: False
  WANDB:
    ENTITY: pinlab-sapienza
    PROJECT: coskad # comment for debug
    GROUP: mld_stdrr
    OFFLINE: false
    RESUME_ID: null
